/********************************************************************************
** Form generated from reading UI file 'moulds.ui'
**
** Created: Thu Aug 25 19:24:34 2016
**      by: Qt User Interface Compiler version 4.7.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MOULDS_H
#define UI_MOULDS_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QComboBox>
#include <QtGui/QGraphicsView>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QPushButton>
#include <QtGui/QTabWidget>
#include <QtGui/QTableWidget>
#include <QtGui/QToolButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Moulds
{
public:
    QTabWidget *tabWidget_U;
    QWidget *tab_2;
    QGroupBox *groupBox_Up_2;
    QLabel *label_41;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLineEdit *lineEdit_D_Height;
    QLineEdit *lineEdit_D_Angle;
    QLineEdit *lineEdit_D_Radius;
    QLineEdit *lineEdit_D_V;
    QLineEdit *lineEdit_D_Speed;
    QLabel *label_14;
    QLabel *label_12;
    QLabel *label_11;
    QLabel *label_8;
    QLabel *label_10;
    QLabel *label_58;
    QTableWidget *tableWidget_LowerMoulds;
    QGraphicsView *graphicsView_D;
    QLabel *label_2;
    QToolButton *pushButton_Left_3;
    QToolButton *pushButton_Left_6;
    QToolButton *pushButton_Left_5;
    QToolButton *pushButton_Left_4;
    QToolButton *pushButton_Left_1;
    QToolButton *pushButton_Left_2;
    QWidget *tab;
    QTableWidget *tableWidget_UpMoulds;
    QGroupBox *groupBox_Up;
    QLineEdit *lineEdit_U_Height;
    QLineEdit *lineEdit_U_Angle;
    QLineEdit *lineEdit_U_Radius;
    QLabel *label_40;
    QLabel *label_42;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_59;
    QGraphicsView *graphicsView_U;
    QLabel *label;
    QToolButton *pushButton_Left_7;
    QToolButton *pushButton_Left_8;
    QToolButton *pushButton_Left_9;
    QToolButton *pushButton_Left_10;
    QToolButton *pushButton_Left_11;
    QToolButton *pushButton_Left_12;
    QWidget *tab_3;
    QLineEdit *lineEdit_D_Height_3;
    QPushButton *pushButton_M_Down;
    QPushButton *pushButton_M_New;
    QPushButton *pushButton_M_Del;
    QTableWidget *tableWidget_Material;
    QLabel *label_28;
    QPushButton *pushButton_M_Up;
    QLabel *label_29;
    QLineEdit *lineEdit_Strengrht;
    QLineEdit *lineEdit_D_Height_4;
    QLabel *label_30;
    QComboBox *comboBox;

    void setupUi(QWidget *Moulds)
    {
        if (Moulds->objectName().isEmpty())
            Moulds->setObjectName(QString::fromUtf8("Moulds"));
        Moulds->resize(1024, 540);
        Moulds->setCursor(QCursor(Qt::ArrowCursor));
        tabWidget_U = new QTabWidget(Moulds);
        tabWidget_U->setObjectName(QString::fromUtf8("tabWidget_U"));
        tabWidget_U->setGeometry(QRect(10, 10, 1005, 521));
        QFont font;
        font.setFamily(QString::fromUtf8("Sans Serif"));
        font.setPointSize(18);
        tabWidget_U->setFont(font);
        tabWidget_U->setCursor(QCursor(Qt::ArrowCursor));
        tabWidget_U->setIconSize(QSize(32, 32));
        tabWidget_U->setUsesScrollButtons(true);
        tabWidget_U->setTabsClosable(false);
        tabWidget_U->setMovable(false);
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        groupBox_Up_2 = new QGroupBox(tab_2);
        groupBox_Up_2->setObjectName(QString::fromUtf8("groupBox_Up_2"));
        groupBox_Up_2->setGeometry(QRect(280, 300, 621, 161));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Sans Serif"));
        font1.setPointSize(12);
        groupBox_Up_2->setFont(font1);
        groupBox_Up_2->setCursor(QCursor(Qt::ArrowCursor));
        label_41 = new QLabel(groupBox_Up_2);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(230, 50, 41, 21));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Sans Serif"));
        font2.setPointSize(14);
        label_41->setFont(font2);
        label_41->setCursor(QCursor(Qt::ArrowCursor));
        label_41->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_44 = new QLabel(groupBox_Up_2);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(230, 90, 41, 21));
        label_44->setFont(font2);
        label_44->setCursor(QCursor(Qt::ArrowCursor));
        label_44->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_45 = new QLabel(groupBox_Up_2);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(550, 90, 41, 21));
        label_45->setFont(font2);
        label_45->setCursor(QCursor(Qt::ArrowCursor));
        label_45->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_46 = new QLabel(groupBox_Up_2);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(550, 50, 41, 21));
        label_46->setFont(font2);
        label_46->setCursor(QCursor(Qt::ArrowCursor));
        label_46->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lineEdit_D_Height = new QLineEdit(groupBox_Up_2);
        lineEdit_D_Height->setObjectName(QString::fromUtf8("lineEdit_D_Height"));
        lineEdit_D_Height->setGeometry(QRect(121, 40, 100, 30));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        palette.setBrush(QPalette::Active, QPalette::Window, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lineEdit_D_Height->setPalette(palette);
        lineEdit_D_Height->setCursor(QCursor(Qt::ArrowCursor));
        lineEdit_D_Height->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_D_Angle = new QLineEdit(groupBox_Up_2);
        lineEdit_D_Angle->setObjectName(QString::fromUtf8("lineEdit_D_Angle"));
        lineEdit_D_Angle->setGeometry(QRect(121, 120, 100, 30));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::Button, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lineEdit_D_Angle->setPalette(palette1);
        lineEdit_D_Angle->setCursor(QCursor(Qt::ArrowCursor));
        lineEdit_D_Angle->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_D_Radius = new QLineEdit(groupBox_Up_2);
        lineEdit_D_Radius->setObjectName(QString::fromUtf8("lineEdit_D_Radius"));
        lineEdit_D_Radius->setGeometry(QRect(441, 80, 100, 30));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::Button, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lineEdit_D_Radius->setPalette(palette2);
        lineEdit_D_Radius->setCursor(QCursor(Qt::ArrowCursor));
        lineEdit_D_Radius->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_D_V = new QLineEdit(groupBox_Up_2);
        lineEdit_D_V->setObjectName(QString::fromUtf8("lineEdit_D_V"));
        lineEdit_D_V->setGeometry(QRect(121, 80, 100, 30));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Button, brush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lineEdit_D_V->setPalette(palette3);
        lineEdit_D_V->setCursor(QCursor(Qt::ArrowCursor));
        lineEdit_D_V->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_D_Speed = new QLineEdit(groupBox_Up_2);
        lineEdit_D_Speed->setObjectName(QString::fromUtf8("lineEdit_D_Speed"));
        lineEdit_D_Speed->setGeometry(QRect(440, 40, 100, 30));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::Button, brush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lineEdit_D_Speed->setPalette(palette4);
        lineEdit_D_Speed->setCursor(QCursor(Qt::ArrowCursor));
        lineEdit_D_Speed->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_14 = new QLabel(groupBox_Up_2);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(30, 40, 90, 24));
        label_14->setFont(font2);
        label_14->setCursor(QCursor(Qt::ArrowCursor));
        label_14->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_12 = new QLabel(groupBox_Up_2);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(30, 120, 90, 24));
        label_12->setFont(font2);
        label_12->setCursor(QCursor(Qt::ArrowCursor));
        label_12->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_11 = new QLabel(groupBox_Up_2);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(320, 82, 111, 24));
        label_11->setFont(font2);
        label_11->setCursor(QCursor(Qt::ArrowCursor));
        label_11->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_8 = new QLabel(groupBox_Up_2);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(30, 80, 90, 24));
        label_8->setFont(font2);
        label_8->setCursor(QCursor(Qt::ArrowCursor));
        label_8->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_10 = new QLabel(groupBox_Up_2);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(320, 40, 111, 24));
        label_10->setFont(font1);
        label_10->setCursor(QCursor(Qt::ArrowCursor));
        label_10->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_58 = new QLabel(groupBox_Up_2);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(230, 130, 31, 16));
        QFont font3;
        font3.setPointSize(14);
        label_58->setFont(font3);
        tableWidget_LowerMoulds = new QTableWidget(tab_2);
        if (tableWidget_LowerMoulds->columnCount() < 8)
            tableWidget_LowerMoulds->setColumnCount(8);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        __qtablewidgetitem->setTextAlignment(Qt::AlignLeft|Qt::AlignVCenter);
        __qtablewidgetitem->setFont(font1);
        tableWidget_LowerMoulds->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QFont font4;
        font4.setPointSize(12);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        __qtablewidgetitem1->setTextAlignment(Qt::AlignLeft|Qt::AlignVCenter);
        __qtablewidgetitem1->setFont(font4);
        tableWidget_LowerMoulds->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        __qtablewidgetitem2->setTextAlignment(Qt::AlignLeft|Qt::AlignVCenter);
        __qtablewidgetitem2->setFont(font1);
        tableWidget_LowerMoulds->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        __qtablewidgetitem3->setTextAlignment(Qt::AlignLeft|Qt::AlignVCenter);
        __qtablewidgetitem3->setFont(font1);
        tableWidget_LowerMoulds->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        __qtablewidgetitem4->setTextAlignment(Qt::AlignLeft|Qt::AlignVCenter);
        __qtablewidgetitem4->setFont(font1);
        tableWidget_LowerMoulds->setHorizontalHeaderItem(4, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        __qtablewidgetitem5->setTextAlignment(Qt::AlignLeft|Qt::AlignVCenter);
        __qtablewidgetitem5->setFont(font1);
        tableWidget_LowerMoulds->setHorizontalHeaderItem(5, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        __qtablewidgetitem6->setTextAlignment(Qt::AlignLeft|Qt::AlignVCenter);
        __qtablewidgetitem6->setFont(font1);
        tableWidget_LowerMoulds->setHorizontalHeaderItem(6, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        __qtablewidgetitem7->setTextAlignment(Qt::AlignLeft|Qt::AlignVCenter);
        __qtablewidgetitem7->setFont(font1);
        tableWidget_LowerMoulds->setHorizontalHeaderItem(7, __qtablewidgetitem7);
        if (tableWidget_LowerMoulds->rowCount() < 50)
            tableWidget_LowerMoulds->setRowCount(50);
        QFont font5;
        font5.setKerning(false);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        __qtablewidgetitem8->setTextAlignment(Qt::AlignHCenter|Qt::AlignVCenter|Qt::AlignCenter);
        __qtablewidgetitem8->setFont(font5);
        tableWidget_LowerMoulds->setItem(0, 0, __qtablewidgetitem8);
        tableWidget_LowerMoulds->setObjectName(QString::fromUtf8("tableWidget_LowerMoulds"));
        tableWidget_LowerMoulds->setGeometry(QRect(280, 30, 621, 261));
        tableWidget_LowerMoulds->setFont(font4);
        tableWidget_LowerMoulds->viewport()->setProperty("cursor", QVariant(QCursor(Qt::ArrowCursor)));
        tableWidget_LowerMoulds->setFrameShadow(QFrame::Sunken);
        tableWidget_LowerMoulds->setMidLineWidth(1);
        tableWidget_LowerMoulds->setVerticalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        tableWidget_LowerMoulds->setEditTriggers(QAbstractItemView::NoEditTriggers);
        tableWidget_LowerMoulds->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidget_LowerMoulds->setSelectionBehavior(QAbstractItemView::SelectRows);
        tableWidget_LowerMoulds->setShowGrid(true);
        tableWidget_LowerMoulds->setSortingEnabled(false);
        tableWidget_LowerMoulds->setCornerButtonEnabled(false);
        tableWidget_LowerMoulds->setRowCount(50);
        tableWidget_LowerMoulds->setColumnCount(8);
        tableWidget_LowerMoulds->horizontalHeader()->setCascadingSectionResizes(false);
        tableWidget_LowerMoulds->horizontalHeader()->setDefaultSectionSize(100);
        tableWidget_LowerMoulds->horizontalHeader()->setMinimumSectionSize(23);
        tableWidget_LowerMoulds->verticalHeader()->setVisible(false);
        tableWidget_LowerMoulds->verticalHeader()->setDefaultSectionSize(30);
        graphicsView_D = new QGraphicsView(tab_2);
        graphicsView_D->setObjectName(QString::fromUtf8("graphicsView_D"));
        graphicsView_D->setGeometry(QRect(10, 30, 250, 431));
        graphicsView_D->viewport()->setProperty("cursor", QVariant(QCursor(Qt::ArrowCursor)));
        label_2 = new QLabel(tab_2);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(20, 40, 230, 410));
        label_2->setPixmap(QPixmap(QString::fromUtf8(":/PIC/ICO/LOWER_MOLD.png")));
        pushButton_Left_3 = new QToolButton(tab_2);
        pushButton_Left_3->setObjectName(QString::fromUtf8("pushButton_Left_3"));
        pushButton_Left_3->setGeometry(QRect(920, 163, 71, 61));
        QFont font6;
        font6.setFamily(QString::fromUtf8("Sans Serif"));
        font6.setPointSize(10);
        pushButton_Left_3->setFont(font6);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/ico/ICO/P1-DEL.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_Left_3->setIcon(icon);
        pushButton_Left_3->setIconSize(QSize(36, 36));
        pushButton_Left_3->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        pushButton_Left_6 = new QToolButton(tab_2);
        pushButton_Left_6->setObjectName(QString::fromUtf8("pushButton_Left_6"));
        pushButton_Left_6->setGeometry(QRect(920, 400, 71, 61));
        pushButton_Left_6->setFont(font6);
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/ico/ICO/P1-COMP.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_Left_6->setIcon(icon1);
        pushButton_Left_6->setIconSize(QSize(36, 36));
        pushButton_Left_6->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        pushButton_Left_5 = new QToolButton(tab_2);
        pushButton_Left_5->setObjectName(QString::fromUtf8("pushButton_Left_5"));
        pushButton_Left_5->setGeometry(QRect(920, 333, 71, 61));
        pushButton_Left_5->setFont(font6);
        pushButton_Left_5->setIconSize(QSize(36, 36));
        pushButton_Left_5->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        pushButton_Left_4 = new QToolButton(tab_2);
        pushButton_Left_4->setObjectName(QString::fromUtf8("pushButton_Left_4"));
        pushButton_Left_4->setGeometry(QRect(920, 230, 71, 61));
        pushButton_Left_4->setFont(font1);
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/ico/ICO/P2-DOWN.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_Left_4->setIcon(icon2);
        pushButton_Left_4->setIconSize(QSize(36, 36));
        pushButton_Left_1 = new QToolButton(tab_2);
        pushButton_Left_1->setObjectName(QString::fromUtf8("pushButton_Left_1"));
        pushButton_Left_1->setGeometry(QRect(920, 30, 71, 61));
        pushButton_Left_1->setFont(font1);
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/ico/ICO/P2-UP.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_Left_1->setIcon(icon3);
        pushButton_Left_1->setIconSize(QSize(36, 36));
        pushButton_Left_1->setToolButtonStyle(Qt::ToolButtonIconOnly);
        pushButton_Left_2 = new QToolButton(tab_2);
        pushButton_Left_2->setObjectName(QString::fromUtf8("pushButton_Left_2"));
        pushButton_Left_2->setGeometry(QRect(920, 97, 71, 61));
        pushButton_Left_2->setFont(font6);
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/ico/ICO/P1-NEW.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_Left_2->setIcon(icon4);
        pushButton_Left_2->setIconSize(QSize(36, 36));
        pushButton_Left_2->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/ico/ICO/P1-LOWER.png"), QSize(), QIcon::Normal, QIcon::Off);
        tabWidget_U->addTab(tab_2, icon5, QString());
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        tableWidget_UpMoulds = new QTableWidget(tab);
        if (tableWidget_UpMoulds->columnCount() < 5)
            tableWidget_UpMoulds->setColumnCount(5);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        __qtablewidgetitem9->setTextAlignment(Qt::AlignLeft|Qt::AlignVCenter);
        __qtablewidgetitem9->setFont(font1);
        tableWidget_UpMoulds->setHorizontalHeaderItem(0, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        __qtablewidgetitem10->setTextAlignment(Qt::AlignLeft|Qt::AlignVCenter);
        __qtablewidgetitem10->setFont(font4);
        tableWidget_UpMoulds->setHorizontalHeaderItem(1, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        __qtablewidgetitem11->setTextAlignment(Qt::AlignLeft|Qt::AlignVCenter);
        __qtablewidgetitem11->setFont(font1);
        tableWidget_UpMoulds->setHorizontalHeaderItem(2, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        __qtablewidgetitem12->setTextAlignment(Qt::AlignLeft|Qt::AlignVCenter);
        __qtablewidgetitem12->setFont(font1);
        tableWidget_UpMoulds->setHorizontalHeaderItem(3, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        __qtablewidgetitem13->setTextAlignment(Qt::AlignLeft|Qt::AlignVCenter);
        __qtablewidgetitem13->setFont(font1);
        tableWidget_UpMoulds->setHorizontalHeaderItem(4, __qtablewidgetitem13);
        if (tableWidget_UpMoulds->rowCount() < 46)
            tableWidget_UpMoulds->setRowCount(46);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        __qtablewidgetitem14->setTextAlignment(Qt::AlignHCenter|Qt::AlignVCenter|Qt::AlignCenter);
        tableWidget_UpMoulds->setItem(0, 0, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        __qtablewidgetitem15->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        tableWidget_UpMoulds->setItem(1, 0, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        __qtablewidgetitem16->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEditable|Qt::ItemIsDragEnabled|Qt::ItemIsDropEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled|Qt::ItemIsTristate);
        tableWidget_UpMoulds->setItem(2, 4, __qtablewidgetitem16);
        tableWidget_UpMoulds->setObjectName(QString::fromUtf8("tableWidget_UpMoulds"));
        tableWidget_UpMoulds->setGeometry(QRect(280, 30, 621, 261));
        QSizePolicy sizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(tableWidget_UpMoulds->sizePolicy().hasHeightForWidth());
        tableWidget_UpMoulds->setSizePolicy(sizePolicy);
        tableWidget_UpMoulds->setFont(font4);
        tableWidget_UpMoulds->viewport()->setProperty("cursor", QVariant(QCursor(Qt::ArrowCursor)));
        tableWidget_UpMoulds->setAcceptDrops(false);
        tableWidget_UpMoulds->setLayoutDirection(Qt::LeftToRight);
        tableWidget_UpMoulds->setMidLineWidth(1);
        tableWidget_UpMoulds->setVerticalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        tableWidget_UpMoulds->setHorizontalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        tableWidget_UpMoulds->setAutoScrollMargin(16);
        tableWidget_UpMoulds->setEditTriggers(QAbstractItemView::NoEditTriggers);
        tableWidget_UpMoulds->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidget_UpMoulds->setSelectionBehavior(QAbstractItemView::SelectRows);
        tableWidget_UpMoulds->setTextElideMode(Qt::ElideRight);
        tableWidget_UpMoulds->setGridStyle(Qt::SolidLine);
        tableWidget_UpMoulds->setSortingEnabled(false);
        tableWidget_UpMoulds->setRowCount(46);
        tableWidget_UpMoulds->setColumnCount(5);
        tableWidget_UpMoulds->horizontalHeader()->setCascadingSectionResizes(false);
        tableWidget_UpMoulds->horizontalHeader()->setMinimumSectionSize(27);
        tableWidget_UpMoulds->horizontalHeader()->setProperty("showSortIndicator", QVariant(false));
        tableWidget_UpMoulds->horizontalHeader()->setStretchLastSection(false);
        tableWidget_UpMoulds->verticalHeader()->setVisible(false);
        tableWidget_UpMoulds->verticalHeader()->setDefaultSectionSize(30);
        tableWidget_UpMoulds->verticalHeader()->setProperty("showSortIndicator", QVariant(false));
        groupBox_Up = new QGroupBox(tab);
        groupBox_Up->setObjectName(QString::fromUtf8("groupBox_Up"));
        groupBox_Up->setGeometry(QRect(280, 300, 621, 161));
        groupBox_Up->setFont(font4);
        groupBox_Up->setCursor(QCursor(Qt::ArrowCursor));
        lineEdit_U_Height = new QLineEdit(groupBox_Up);
        lineEdit_U_Height->setObjectName(QString::fromUtf8("lineEdit_U_Height"));
        lineEdit_U_Height->setGeometry(QRect(128, 40, 100, 30));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::Button, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lineEdit_U_Height->setPalette(palette5);
        lineEdit_U_Height->setCursor(QCursor(Qt::ArrowCursor));
        lineEdit_U_Height->setFocusPolicy(Qt::ClickFocus);
        lineEdit_U_Height->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_U_Height->setEchoMode(QLineEdit::Normal);
        //lineEdit_U_Height->setCursorMoveStyle(Qt::VisualMoveStyle);
        lineEdit_U_Angle = new QLineEdit(groupBox_Up);
        lineEdit_U_Angle->setObjectName(QString::fromUtf8("lineEdit_U_Angle"));
        lineEdit_U_Angle->setGeometry(QRect(128, 90, 100, 30));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::Button, brush);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lineEdit_U_Angle->setPalette(palette6);
        lineEdit_U_Angle->setCursor(QCursor(Qt::ArrowCursor));
        lineEdit_U_Angle->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_U_Radius = new QLineEdit(groupBox_Up);
        lineEdit_U_Radius->setObjectName(QString::fromUtf8("lineEdit_U_Radius"));
        lineEdit_U_Radius->setGeometry(QRect(430, 40, 100, 30));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::Button, brush);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lineEdit_U_Radius->setPalette(palette7);
        lineEdit_U_Radius->setCursor(QCursor(Qt::ArrowCursor));
        lineEdit_U_Radius->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_40 = new QLabel(groupBox_Up);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(230, 50, 41, 21));
        label_40->setFont(font3);
        label_40->setCursor(QCursor(Qt::ArrowCursor));
        label_40->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_42 = new QLabel(groupBox_Up);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(530, 50, 41, 21));
        label_42->setFont(font3);
        label_42->setCursor(QCursor(Qt::ArrowCursor));
        label_42->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_15 = new QLabel(groupBox_Up);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(50, 40, 90, 24));
        label_15->setFont(font3);
        label_15->setCursor(QCursor(Qt::ArrowCursor));
        label_15->setTextFormat(Qt::RichText);
        label_15->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_16 = new QLabel(groupBox_Up);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(50, 90, 90, 24));
        label_16->setFont(font3);
        label_16->setCursor(QCursor(Qt::ArrowCursor));
        label_16->setTextFormat(Qt::RichText);
        label_16->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_17 = new QLabel(groupBox_Up);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(340, 40, 90, 24));
        label_17->setFont(font3);
        label_17->setCursor(QCursor(Qt::ArrowCursor));
        label_17->setTextFormat(Qt::RichText);
        label_17->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_59 = new QLabel(groupBox_Up);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(240, 100, 31, 16));
        label_59->setFont(font3);
        graphicsView_U = new QGraphicsView(tab);
        graphicsView_U->setObjectName(QString::fromUtf8("graphicsView_U"));
        graphicsView_U->setGeometry(QRect(10, 30, 250, 431));
        graphicsView_U->viewport()->setProperty("cursor", QVariant(QCursor(Qt::ArrowCursor)));
        label = new QLabel(tab);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(20, 40, 230, 410));
        label->setPixmap(QPixmap(QString::fromUtf8(":/PIC/ICO/UP_MOLD.png")));
        pushButton_Left_7 = new QToolButton(tab);
        pushButton_Left_7->setObjectName(QString::fromUtf8("pushButton_Left_7"));
        pushButton_Left_7->setGeometry(QRect(920, 400, 71, 61));
        pushButton_Left_7->setFont(font6);
        pushButton_Left_7->setIconSize(QSize(36, 36));
        pushButton_Left_7->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        pushButton_Left_8 = new QToolButton(tab);
        pushButton_Left_8->setObjectName(QString::fromUtf8("pushButton_Left_8"));
        pushButton_Left_8->setGeometry(QRect(920, 97, 71, 61));
        pushButton_Left_8->setFont(font6);
        pushButton_Left_8->setIcon(icon4);
        pushButton_Left_8->setIconSize(QSize(36, 36));
        pushButton_Left_8->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        pushButton_Left_9 = new QToolButton(tab);
        pushButton_Left_9->setObjectName(QString::fromUtf8("pushButton_Left_9"));
        pushButton_Left_9->setGeometry(QRect(920, 230, 71, 61));
        pushButton_Left_9->setFont(font1);
        pushButton_Left_9->setIcon(icon2);
        pushButton_Left_9->setIconSize(QSize(36, 36));
        pushButton_Left_10 = new QToolButton(tab);
        pushButton_Left_10->setObjectName(QString::fromUtf8("pushButton_Left_10"));
        pushButton_Left_10->setGeometry(QRect(920, 163, 71, 61));
        pushButton_Left_10->setFont(font6);
        pushButton_Left_10->setIcon(icon);
        pushButton_Left_10->setIconSize(QSize(36, 36));
        pushButton_Left_10->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        pushButton_Left_11 = new QToolButton(tab);
        pushButton_Left_11->setObjectName(QString::fromUtf8("pushButton_Left_11"));
        pushButton_Left_11->setGeometry(QRect(920, 333, 71, 61));
        pushButton_Left_11->setFont(font6);
        pushButton_Left_11->setIconSize(QSize(36, 36));
        pushButton_Left_11->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        pushButton_Left_12 = new QToolButton(tab);
        pushButton_Left_12->setObjectName(QString::fromUtf8("pushButton_Left_12"));
        pushButton_Left_12->setGeometry(QRect(920, 30, 71, 61));
        pushButton_Left_12->setFont(font1);
        pushButton_Left_12->setIcon(icon3);
        pushButton_Left_12->setIconSize(QSize(36, 36));
        pushButton_Left_12->setToolButtonStyle(Qt::ToolButtonIconOnly);
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/ico/ICO/P1-UPER.png"), QSize(), QIcon::Normal, QIcon::Off);
        tabWidget_U->addTab(tab, icon6, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        lineEdit_D_Height_3 = new QLineEdit(tab_3);
        lineEdit_D_Height_3->setObjectName(QString::fromUtf8("lineEdit_D_Height_3"));
        lineEdit_D_Height_3->setGeometry(QRect(190, 390, 93, 26));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::Button, brush);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lineEdit_D_Height_3->setPalette(palette8);
        lineEdit_D_Height_3->setCursor(QCursor(Qt::ArrowCursor));
        lineEdit_D_Height_3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        pushButton_M_Down = new QPushButton(tab_3);
        pushButton_M_Down->setObjectName(QString::fromUtf8("pushButton_M_Down"));
        pushButton_M_Down->setGeometry(QRect(940, 220, 61, 51));
        QFont font7;
        font7.setPointSize(18);
        pushButton_M_Down->setFont(font7);
        pushButton_M_Down->setCursor(QCursor(Qt::ArrowCursor));
        pushButton_M_New = new QPushButton(tab_3);
        pushButton_M_New->setObjectName(QString::fromUtf8("pushButton_M_New"));
        pushButton_M_New->setGeometry(QRect(940, 100, 61, 51));
        pushButton_M_New->setFont(font7);
        pushButton_M_New->setCursor(QCursor(Qt::ArrowCursor));
        pushButton_M_Del = new QPushButton(tab_3);
        pushButton_M_Del->setObjectName(QString::fromUtf8("pushButton_M_Del"));
        pushButton_M_Del->setGeometry(QRect(940, 160, 61, 51));
        pushButton_M_Del->setFont(font7);
        pushButton_M_Del->setCursor(QCursor(Qt::ArrowCursor));
        tableWidget_Material = new QTableWidget(tab_3);
        if (tableWidget_Material->columnCount() < 4)
            tableWidget_Material->setColumnCount(4);
        QFont font8;
        font8.setFamily(QString::fromUtf8("\346\226\207\346\263\211\351\251\277\345\276\256\347\261\263\351\273\221"));
        font8.setPointSize(12);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        __qtablewidgetitem17->setFont(font8);
        tableWidget_Material->setHorizontalHeaderItem(0, __qtablewidgetitem17);
        QFont font9;
        font9.setPointSize(15);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        __qtablewidgetitem18->setFont(font9);
        tableWidget_Material->setHorizontalHeaderItem(1, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        __qtablewidgetitem19->setFont(font8);
        tableWidget_Material->setHorizontalHeaderItem(2, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        __qtablewidgetitem20->setFont(font8);
        tableWidget_Material->setHorizontalHeaderItem(3, __qtablewidgetitem20);
        if (tableWidget_Material->rowCount() < 50)
            tableWidget_Material->setRowCount(50);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        __qtablewidgetitem21->setTextAlignment(Qt::AlignHCenter|Qt::AlignVCenter|Qt::AlignCenter);
        __qtablewidgetitem21->setFont(font5);
        tableWidget_Material->setItem(0, 0, __qtablewidgetitem21);
        tableWidget_Material->setObjectName(QString::fromUtf8("tableWidget_Material"));
        tableWidget_Material->setGeometry(QRect(10, 20, 801, 311));
        tableWidget_Material->setFont(font4);
        tableWidget_Material->viewport()->setProperty("cursor", QVariant(QCursor(Qt::ArrowCursor)));
        tableWidget_Material->setFrameShadow(QFrame::Sunken);
        tableWidget_Material->setMidLineWidth(1);
        tableWidget_Material->setVerticalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        tableWidget_Material->setEditTriggers(QAbstractItemView::NoEditTriggers);
        tableWidget_Material->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidget_Material->setSelectionBehavior(QAbstractItemView::SelectRows);
        tableWidget_Material->setShowGrid(true);
        tableWidget_Material->setSortingEnabled(false);
        tableWidget_Material->setCornerButtonEnabled(false);
        tableWidget_Material->setRowCount(50);
        tableWidget_Material->setColumnCount(4);
        tableWidget_Material->horizontalHeader()->setCascadingSectionResizes(false);
        tableWidget_Material->horizontalHeader()->setDefaultSectionSize(100);
        tableWidget_Material->horizontalHeader()->setMinimumSectionSize(23);
        tableWidget_Material->verticalHeader()->setVisible(false);
        tableWidget_Material->verticalHeader()->setDefaultSectionSize(30);
        label_28 = new QLabel(tab_3);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(40, 430, 111, 24));
        label_28->setFont(font9);
        label_28->setCursor(QCursor(Qt::ArrowCursor));
        label_28->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        pushButton_M_Up = new QPushButton(tab_3);
        pushButton_M_Up->setObjectName(QString::fromUtf8("pushButton_M_Up"));
        pushButton_M_Up->setGeometry(QRect(940, 40, 61, 51));
        pushButton_M_Up->setFont(font7);
        pushButton_M_Up->setCursor(QCursor(Qt::ArrowCursor));
        pushButton_M_Up->setAutoDefault(false);
        label_29 = new QLabel(tab_3);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(40, 390, 101, 24));
        label_29->setFont(font9);
        label_29->setCursor(QCursor(Qt::ArrowCursor));
        label_29->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lineEdit_Strengrht = new QLineEdit(tab_3);
        lineEdit_Strengrht->setObjectName(QString::fromUtf8("lineEdit_Strengrht"));
        lineEdit_Strengrht->setGeometry(QRect(190, 430, 93, 26));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::Button, brush);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lineEdit_Strengrht->setPalette(palette9);
        lineEdit_Strengrht->setCursor(QCursor(Qt::ArrowCursor));
        lineEdit_Strengrht->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_D_Height_4 = new QLineEdit(tab_3);
        lineEdit_D_Height_4->setObjectName(QString::fromUtf8("lineEdit_D_Height_4"));
        lineEdit_D_Height_4->setGeometry(QRect(300, 350, 93, 26));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::Button, brush);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lineEdit_D_Height_4->setPalette(palette10);
        lineEdit_D_Height_4->setCursor(QCursor(Qt::ArrowCursor));
        lineEdit_D_Height_4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_30 = new QLabel(tab_3);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(40, 350, 101, 24));
        label_30->setFont(font9);
        label_30->setCursor(QCursor(Qt::ArrowCursor));
        label_30->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        comboBox = new QComboBox(tab_3);
        comboBox->setObjectName(QString::fromUtf8("comboBox"));
        comboBox->setGeometry(QRect(190, 350, 90, 25));
        QIcon icon7;
        icon7.addFile(QString::fromUtf8(":/ico/ICO/P1-MET.png"), QSize(), QIcon::Normal, QIcon::Off);
        tabWidget_U->addTab(tab_3, icon7, QString());

        retranslateUi(Moulds);

        tabWidget_U->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(Moulds);
    } // setupUi

    void retranslateUi(QWidget *Moulds)
    {
        Moulds->setWindowTitle(QApplication::translate("Moulds", "Form", 0, QApplication::UnicodeUTF8));
        groupBox_Up_2->setTitle(QApplication::translate("Moulds", "\345\217\202\346\225\260", 0, QApplication::UnicodeUTF8));
        label_41->setText(QApplication::translate("Moulds", "mm", 0, QApplication::UnicodeUTF8));
        label_44->setText(QApplication::translate("Moulds", "mm", 0, QApplication::UnicodeUTF8));
        label_45->setText(QApplication::translate("Moulds", "mm", 0, QApplication::UnicodeUTF8));
        label_46->setText(QApplication::translate("Moulds", "mm", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("Moulds", "\351\253\230\345\272\246(H)", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("Moulds", "\350\247\222\345\272\246(A)", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("Moulds", "\345\215\212\345\276\204(RA)", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("Moulds", "V\345\274\200\345\217\243(V)", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("Moulds", "X\345\256\211\345\205\250\344\275\215\347\275\256(SN)", 0, QApplication::UnicodeUTF8));
        label_58->setText(QApplication::translate("Moulds", "\302\260", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem = tableWidget_LowerMoulds->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("Moulds", "\346\250\241\345\205\267\345\217\267", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidget_LowerMoulds->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("Moulds", "\351\253\230\345\272\246", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidget_LowerMoulds->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QApplication::translate("Moulds", "\346\247\275\345\217\243", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidget_LowerMoulds->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QApplication::translate("Moulds", "\350\247\222\345\272\246", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidget_LowerMoulds->horizontalHeaderItem(4);
        ___qtablewidgetitem4->setText(QApplication::translate("Moulds", "\345\215\212\345\276\204", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidget_LowerMoulds->horizontalHeaderItem(5);
        ___qtablewidgetitem5->setText(QApplication::translate("Moulds", "\351\200\237\345\272\246\350\275\254\346\215\242\347\202\271", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidget_LowerMoulds->horizontalHeaderItem(6);
        ___qtablewidgetitem6->setText(QApplication::translate("Moulds", "X\350\275\264\345\256\211\345\205\250\345\214\272\345\237\237", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidget_LowerMoulds->horizontalHeaderItem(7);
        ___qtablewidgetitem7->setText(QApplication::translate("Moulds", "\351\230\273\346\212\227", 0, QApplication::UnicodeUTF8));

        const bool __sortingEnabled = tableWidget_LowerMoulds->isSortingEnabled();
        tableWidget_LowerMoulds->setSortingEnabled(false);
        tableWidget_LowerMoulds->setSortingEnabled(__sortingEnabled);

        label_2->setText(QString());
        pushButton_Left_3->setText(QApplication::translate("Moulds", "\345\210\240\351\231\244", 0, QApplication::UnicodeUTF8));
        pushButton_Left_6->setText(QApplication::translate("Moulds", "\346\212\230\345\274\257\344\277\256\346\255\243", 0, QApplication::UnicodeUTF8));
        pushButton_Left_4->setText(QApplication::translate("Moulds", "down", 0, QApplication::UnicodeUTF8));
        pushButton_Left_1->setText(QApplication::translate("Moulds", "UP", 0, QApplication::UnicodeUTF8));
        pushButton_Left_2->setText(QApplication::translate("Moulds", "\346\226\260\345\273\272", 0, QApplication::UnicodeUTF8));
        tabWidget_U->setTabText(tabWidget_U->indexOf(tab_2), QApplication::translate("Moulds", " \344\270\213\346\250\241\345\272\223     ", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem8 = tableWidget_UpMoulds->horizontalHeaderItem(0);
        ___qtablewidgetitem8->setText(QApplication::translate("Moulds", "\346\250\241\345\205\267\345\217\267", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem9 = tableWidget_UpMoulds->horizontalHeaderItem(1);
        ___qtablewidgetitem9->setText(QApplication::translate("Moulds", "\350\247\222\345\272\246", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem10 = tableWidget_UpMoulds->horizontalHeaderItem(2);
        ___qtablewidgetitem10->setText(QApplication::translate("Moulds", "\351\253\230\345\272\246", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem11 = tableWidget_UpMoulds->horizontalHeaderItem(3);
        ___qtablewidgetitem11->setText(QApplication::translate("Moulds", "\345\215\212\345\276\204", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem12 = tableWidget_UpMoulds->horizontalHeaderItem(4);
        ___qtablewidgetitem12->setText(QApplication::translate("Moulds", "\351\230\273\346\212\227", 0, QApplication::UnicodeUTF8));

        const bool __sortingEnabled1 = tableWidget_UpMoulds->isSortingEnabled();
        tableWidget_UpMoulds->setSortingEnabled(false);
        tableWidget_UpMoulds->setSortingEnabled(__sortingEnabled1);

        groupBox_Up->setTitle(QApplication::translate("Moulds", "\345\217\202\346\225\260 ", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("Moulds", "mm", 0, QApplication::UnicodeUTF8));
        label_42->setText(QApplication::translate("Moulds", "mm", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("Moulds", "\351\253\230\345\272\246(H)", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("Moulds", "\350\247\222\345\272\246(a)", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("Moulds", "\345\215\212\345\276\204(RA)", 0, QApplication::UnicodeUTF8));
        label_59->setText(QApplication::translate("Moulds", "\302\260", 0, QApplication::UnicodeUTF8));
        label->setText(QString());
        pushButton_Left_8->setText(QApplication::translate("Moulds", "\346\226\260\345\273\272", 0, QApplication::UnicodeUTF8));
        pushButton_Left_9->setText(QApplication::translate("Moulds", "down", 0, QApplication::UnicodeUTF8));
        pushButton_Left_10->setText(QApplication::translate("Moulds", "\345\210\240\351\231\244", 0, QApplication::UnicodeUTF8));
        pushButton_Left_12->setText(QApplication::translate("Moulds", "UP", 0, QApplication::UnicodeUTF8));
        tabWidget_U->setTabText(tabWidget_U->indexOf(tab), QApplication::translate("Moulds", " \344\270\212\346\250\241\345\272\223     ", 0, QApplication::UnicodeUTF8));
        pushButton_M_Down->setText(QApplication::translate("Moulds", "\345\220\221\344\270\213", 0, QApplication::UnicodeUTF8));
        pushButton_M_New->setText(QApplication::translate("Moulds", "\346\226\260\345\273\272", 0, QApplication::UnicodeUTF8));
        pushButton_M_Del->setText(QApplication::translate("Moulds", "\345\210\240\351\231\244", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem13 = tableWidget_Material->horizontalHeaderItem(0);
        ___qtablewidgetitem13->setText(QApplication::translate("Moulds", "\346\235\220\346\226\231\345\217\267", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem14 = tableWidget_Material->horizontalHeaderItem(1);
        ___qtablewidgetitem14->setText(QApplication::translate("Moulds", "\345\220\215\347\247\260", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem15 = tableWidget_Material->horizontalHeaderItem(2);
        ___qtablewidgetitem15->setText(QApplication::translate("Moulds", "\346\212\227\346\213\211\347\263\273\346\225\260", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem16 = tableWidget_Material->horizontalHeaderItem(3);
        ___qtablewidgetitem16->setText(QApplication::translate("Moulds", "E-\346\250\241\346\225\260", 0, QApplication::UnicodeUTF8));

        const bool __sortingEnabled2 = tableWidget_Material->isSortingEnabled();
        tableWidget_Material->setSortingEnabled(false);
        tableWidget_Material->setSortingEnabled(__sortingEnabled2);

        label_28->setText(QApplication::translate("Moulds", "E-\346\250\241\346\225\260", 0, QApplication::UnicodeUTF8));
        pushButton_M_Up->setText(QApplication::translate("Moulds", "\345\220\221\344\270\212", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("Moulds", "\346\212\227\346\213\211\347\263\273\346\225\260", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("Moulds", "\345\220\215\347\247\260", 0, QApplication::UnicodeUTF8));
        comboBox->clear();
        comboBox->insertItems(0, QStringList()
         << QApplication::translate("Moulds", "\351\223\235", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("Moulds", "\344\270\215\347\273\243\351\222\242", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("Moulds", "\351\223\201", 0, QApplication::UnicodeUTF8)
        );
        tabWidget_U->setTabText(tabWidget_U->indexOf(tab_3), QApplication::translate("Moulds", " \346\235\220\346\226\231\345\272\223      ", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Moulds: public Ui_Moulds {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MOULDS_H
