/********************************************************************************
** Form generated from reading UI file 'programname.ui'
**
** Created: Thu Aug 25 10:38:46 2016
**      by: Qt User Interface Compiler version 4.7.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PROGRAMNAME_H
#define UI_PROGRAMNAME_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QDialog>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_ProgramName
{
public:
    QLabel *label;
    QLineEdit *lineEdit_programName;
    QLabel *label_isEmpty;
    QPushButton *panelButton_b;
    QPushButton *panelButton_a;
    QPushButton *panelButton_r;
    QPushButton *panelButton_v;
    QPushButton *panelButton_j;
    QPushButton *BackButton;
    QPushButton *panelButton_f;
    QPushButton *panelButton_5;
    QPushButton *panelButton_2;
    QPushButton *panelButton_x;
    QPushButton *programName_confirm;
    QPushButton *panelButton_4;
    QPushButton *panelButton_o;
    QPushButton *panelButton_c;
    QPushButton *panelButton_i;
    QPushButton *panelButton_p;
    QPushButton *panelButton_Dec;
    QPushButton *panelButton_y;
    QPushButton *panelButton_h;
    QPushButton *panelButton_0;
    QPushButton *panelButton_8;
    QPushButton *panelButton_e;
    QPushButton *panelButton_t;
    QPushButton *panelButton_m;
    QPushButton *panelButton_Plus;
    QPushButton *panelButton_d;
    QPushButton *panelButton_u;
    QPushButton *panelButton_w;
    QPushButton *panelButton_n;
    QPushButton *panelButton_s;
    QPushButton *panelButton_7;
    QPushButton *panelButton_g;
    QPushButton *panelButton_q;
    QPushButton *panelButton_9;
    QPushButton *panelButton_1;
    QPushButton *panelButton_6;
    QPushButton *panelButton_z;
    QPushButton *panelButton_star;
    QPushButton *panelButton_3;
    QPushButton *panelButton_k;
    QPushButton *programName_cancal;
    QPushButton *panelButton_l;

    void setupUi(QDialog *ProgramName)
    {
        if (ProgramName->objectName().isEmpty())
            ProgramName->setObjectName(QString::fromUtf8("ProgramName"));
        ProgramName->resize(617, 315);
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        QBrush brush1(QColor(85, 85, 127, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        ProgramName->setPalette(palette);
        label = new QLabel(ProgramName);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(42, 50, 131, 31));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QBrush brush2(QColor(106, 104, 100, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        label->setPalette(palette1);
        QFont font;
        font.setFamily(QString::fromUtf8("\346\226\207\346\263\211\351\251\277\345\276\256\347\261\263\351\273\221"));
        font.setPointSize(16);
        label->setFont(font);
        lineEdit_programName = new QLineEdit(ProgramName);
        lineEdit_programName->setObjectName(QString::fromUtf8("lineEdit_programName"));
        lineEdit_programName->setGeometry(QRect(180, 50, 201, 31));
        lineEdit_programName->setFont(font);
        lineEdit_programName->setFocusPolicy(Qt::WheelFocus);
        lineEdit_programName->setReadOnly(true);
        label_isEmpty = new QLabel(ProgramName);
        label_isEmpty->setObjectName(QString::fromUtf8("label_isEmpty"));
        label_isEmpty->setGeometry(QRect(400, 55, 171, 21));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        label_isEmpty->setPalette(palette2);
        QFont font1;
        font1.setFamily(QString::fromUtf8("\346\226\207\346\263\211\351\251\277\345\276\256\347\261\263\351\273\221"));
        font1.setPointSize(12);
        label_isEmpty->setFont(font1);
        panelButton_b = new QPushButton(ProgramName);
        panelButton_b->setObjectName(QString::fromUtf8("panelButton_b"));
        panelButton_b->setGeometry(QRect(226, 244, 45, 40));
        QSizePolicy sizePolicy(QSizePolicy::Minimum, QSizePolicy::Minimum);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(panelButton_b->sizePolicy().hasHeightForWidth());
        panelButton_b->setSizePolicy(sizePolicy);
        panelButton_b->setMinimumSize(QSize(45, 40));
        QFont font2;
        font2.setPointSize(11);
        panelButton_b->setFont(font2);
        panelButton_b->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_b->setFocusPolicy(Qt::NoFocus);
        panelButton_b->setProperty("buttonValue", QVariant(QChar(98)));
        panelButton_a = new QPushButton(ProgramName);
        panelButton_a->setObjectName(QString::fromUtf8("panelButton_a"));
        panelButton_a->setGeometry(QRect(62, 202, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_a->sizePolicy().hasHeightForWidth());
        panelButton_a->setSizePolicy(sizePolicy);
        panelButton_a->setMinimumSize(QSize(45, 40));
        panelButton_a->setFont(font2);
        panelButton_a->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_a->setFocusPolicy(Qt::NoFocus);
        panelButton_a->setProperty("buttonValue", QVariant(QChar(97)));
        panelButton_r = new QPushButton(ProgramName);
        panelButton_r->setObjectName(QString::fromUtf8("panelButton_r"));
        panelButton_r->setGeometry(QRect(180, 160, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_r->sizePolicy().hasHeightForWidth());
        panelButton_r->setSizePolicy(sizePolicy);
        panelButton_r->setMinimumSize(QSize(45, 40));
        panelButton_r->setFont(font2);
        panelButton_r->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_r->setFocusPolicy(Qt::NoFocus);
        panelButton_r->setProperty("buttonValue", QVariant(QChar(114)));
        panelButton_v = new QPushButton(ProgramName);
        panelButton_v->setObjectName(QString::fromUtf8("panelButton_v"));
        panelButton_v->setGeometry(QRect(180, 244, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_v->sizePolicy().hasHeightForWidth());
        panelButton_v->setSizePolicy(sizePolicy);
        panelButton_v->setMinimumSize(QSize(45, 40));
        panelButton_v->setFont(font2);
        panelButton_v->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_v->setFocusPolicy(Qt::NoFocus);
        panelButton_v->setProperty("buttonValue", QVariant(QChar(118)));
        panelButton_j = new QPushButton(ProgramName);
        panelButton_j->setObjectName(QString::fromUtf8("panelButton_j"));
        panelButton_j->setGeometry(QRect(338, 202, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_j->sizePolicy().hasHeightForWidth());
        panelButton_j->setSizePolicy(sizePolicy);
        panelButton_j->setMinimumSize(QSize(45, 40));
        panelButton_j->setFont(font2);
        panelButton_j->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_j->setFocusPolicy(Qt::NoFocus);
        panelButton_j->setProperty("buttonValue", QVariant(QChar(106)));
        BackButton = new QPushButton(ProgramName);
        BackButton->setObjectName(QString::fromUtf8("BackButton"));
        BackButton->setGeometry(QRect(512, 115, 61, 40));
        sizePolicy.setHeightForWidth(BackButton->sizePolicy().hasHeightForWidth());
        BackButton->setSizePolicy(sizePolicy);
        BackButton->setMinimumSize(QSize(45, 40));
        BackButton->setFont(font1);
        BackButton->setCursor(QCursor(Qt::ArrowCursor));
        BackButton->setFocusPolicy(Qt::NoFocus);
        BackButton->setProperty("buttonValue", QVariant(QChar(0)));
        panelButton_f = new QPushButton(ProgramName);
        panelButton_f->setObjectName(QString::fromUtf8("panelButton_f"));
        panelButton_f->setGeometry(QRect(200, 202, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_f->sizePolicy().hasHeightForWidth());
        panelButton_f->setSizePolicy(sizePolicy);
        panelButton_f->setMinimumSize(QSize(45, 40));
        panelButton_f->setFont(font2);
        panelButton_f->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_f->setFocusPolicy(Qt::NoFocus);
        panelButton_f->setProperty("buttonValue", QVariant(QChar(102)));
        panelButton_5 = new QPushButton(ProgramName);
        panelButton_5->setObjectName(QString::fromUtf8("panelButton_5"));
        panelButton_5->setGeometry(QRect(226, 115, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_5->sizePolicy().hasHeightForWidth());
        panelButton_5->setSizePolicy(sizePolicy);
        panelButton_5->setMinimumSize(QSize(45, 40));
        panelButton_5->setFont(font2);
        panelButton_5->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_5->setFocusPolicy(Qt::NoFocus);
        panelButton_5->setProperty("buttonValue", QVariant(QChar(53)));
        panelButton_2 = new QPushButton(ProgramName);
        panelButton_2->setObjectName(QString::fromUtf8("panelButton_2"));
        panelButton_2->setGeometry(QRect(88, 115, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_2->sizePolicy().hasHeightForWidth());
        panelButton_2->setSizePolicy(sizePolicy);
        panelButton_2->setMinimumSize(QSize(45, 40));
        panelButton_2->setFont(font2);
        panelButton_2->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_2->setFocusPolicy(Qt::NoFocus);
        panelButton_2->setProperty("buttonValue", QVariant(QChar(50)));
        panelButton_x = new QPushButton(ProgramName);
        panelButton_x->setObjectName(QString::fromUtf8("panelButton_x"));
        panelButton_x->setGeometry(QRect(88, 244, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_x->sizePolicy().hasHeightForWidth());
        panelButton_x->setSizePolicy(sizePolicy);
        panelButton_x->setMinimumSize(QSize(45, 40));
        panelButton_x->setFont(font2);
        panelButton_x->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_x->setFocusPolicy(Qt::NoFocus);
        panelButton_x->setProperty("buttonValue", QVariant(QChar(120)));
        programName_confirm = new QPushButton(ProgramName);
        programName_confirm->setObjectName(QString::fromUtf8("programName_confirm"));
        programName_confirm->setGeometry(QRect(512, 202, 61, 82));
        programName_confirm->setFont(font1);
        panelButton_4 = new QPushButton(ProgramName);
        panelButton_4->setObjectName(QString::fromUtf8("panelButton_4"));
        panelButton_4->setGeometry(QRect(180, 115, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_4->sizePolicy().hasHeightForWidth());
        panelButton_4->setSizePolicy(sizePolicy);
        panelButton_4->setMinimumSize(QSize(45, 40));
        panelButton_4->setFont(font2);
        panelButton_4->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_4->setFocusPolicy(Qt::NoFocus);
        panelButton_4->setProperty("buttonValue", QVariant(QChar(52)));
        panelButton_o = new QPushButton(ProgramName);
        panelButton_o->setObjectName(QString::fromUtf8("panelButton_o"));
        panelButton_o->setGeometry(QRect(410, 160, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_o->sizePolicy().hasHeightForWidth());
        panelButton_o->setSizePolicy(sizePolicy);
        panelButton_o->setMinimumSize(QSize(45, 40));
        panelButton_o->setFont(font2);
        panelButton_o->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_o->setFocusPolicy(Qt::NoFocus);
        panelButton_o->setProperty("buttonValue", QVariant(QChar(111)));
        panelButton_c = new QPushButton(ProgramName);
        panelButton_c->setObjectName(QString::fromUtf8("panelButton_c"));
        panelButton_c->setGeometry(QRect(134, 244, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_c->sizePolicy().hasHeightForWidth());
        panelButton_c->setSizePolicy(sizePolicy);
        panelButton_c->setMinimumSize(QSize(45, 40));
        panelButton_c->setFont(font2);
        panelButton_c->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_c->setFocusPolicy(Qt::NoFocus);
        panelButton_c->setProperty("buttonValue", QVariant(QChar(99)));
        panelButton_i = new QPushButton(ProgramName);
        panelButton_i->setObjectName(QString::fromUtf8("panelButton_i"));
        panelButton_i->setGeometry(QRect(364, 160, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_i->sizePolicy().hasHeightForWidth());
        panelButton_i->setSizePolicy(sizePolicy);
        panelButton_i->setMinimumSize(QSize(45, 40));
        panelButton_i->setFont(font2);
        panelButton_i->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_i->setFocusPolicy(Qt::NoFocus);
        panelButton_i->setProperty("buttonValue", QVariant(QChar(105)));
        panelButton_p = new QPushButton(ProgramName);
        panelButton_p->setObjectName(QString::fromUtf8("panelButton_p"));
        panelButton_p->setGeometry(QRect(456, 160, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_p->sizePolicy().hasHeightForWidth());
        panelButton_p->setSizePolicy(sizePolicy);
        panelButton_p->setMinimumSize(QSize(45, 40));
        panelButton_p->setFont(font2);
        panelButton_p->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_p->setFocusPolicy(Qt::NoFocus);
        panelButton_p->setProperty("buttonValue", QVariant(QChar(112)));
        panelButton_Dec = new QPushButton(ProgramName);
        panelButton_Dec->setObjectName(QString::fromUtf8("panelButton_Dec"));
        panelButton_Dec->setGeometry(QRect(410, 244, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_Dec->sizePolicy().hasHeightForWidth());
        panelButton_Dec->setSizePolicy(sizePolicy);
        panelButton_Dec->setMinimumSize(QSize(45, 40));
        panelButton_Dec->setFont(font2);
        panelButton_Dec->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_Dec->setFocusPolicy(Qt::NoFocus);
        panelButton_Dec->setProperty("buttonValue", QVariant(QChar(45)));
        panelButton_y = new QPushButton(ProgramName);
        panelButton_y->setObjectName(QString::fromUtf8("panelButton_y"));
        panelButton_y->setGeometry(QRect(272, 160, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_y->sizePolicy().hasHeightForWidth());
        panelButton_y->setSizePolicy(sizePolicy);
        panelButton_y->setMinimumSize(QSize(45, 40));
        panelButton_y->setFont(font2);
        panelButton_y->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_y->setFocusPolicy(Qt::NoFocus);
        panelButton_y->setProperty("buttonValue", QVariant(QChar(121)));
        panelButton_h = new QPushButton(ProgramName);
        panelButton_h->setObjectName(QString::fromUtf8("panelButton_h"));
        panelButton_h->setGeometry(QRect(292, 202, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_h->sizePolicy().hasHeightForWidth());
        panelButton_h->setSizePolicy(sizePolicy);
        panelButton_h->setMinimumSize(QSize(45, 40));
        panelButton_h->setFont(font2);
        panelButton_h->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_h->setFocusPolicy(Qt::NoFocus);
        panelButton_h->setProperty("buttonValue", QVariant(QChar(104)));
        panelButton_0 = new QPushButton(ProgramName);
        panelButton_0->setObjectName(QString::fromUtf8("panelButton_0"));
        panelButton_0->setGeometry(QRect(456, 115, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_0->sizePolicy().hasHeightForWidth());
        panelButton_0->setSizePolicy(sizePolicy);
        panelButton_0->setMinimumSize(QSize(45, 40));
        panelButton_0->setFont(font2);
        panelButton_0->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_0->setFocusPolicy(Qt::NoFocus);
        panelButton_0->setProperty("buttonValue", QVariant(QChar(48)));
        panelButton_8 = new QPushButton(ProgramName);
        panelButton_8->setObjectName(QString::fromUtf8("panelButton_8"));
        panelButton_8->setGeometry(QRect(364, 115, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_8->sizePolicy().hasHeightForWidth());
        panelButton_8->setSizePolicy(sizePolicy);
        panelButton_8->setMinimumSize(QSize(45, 40));
        panelButton_8->setFont(font2);
        panelButton_8->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_8->setFocusPolicy(Qt::NoFocus);
        panelButton_8->setProperty("buttonValue", QVariant(QChar(56)));
        panelButton_e = new QPushButton(ProgramName);
        panelButton_e->setObjectName(QString::fromUtf8("panelButton_e"));
        panelButton_e->setGeometry(QRect(134, 160, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_e->sizePolicy().hasHeightForWidth());
        panelButton_e->setSizePolicy(sizePolicy);
        panelButton_e->setMinimumSize(QSize(45, 40));
        panelButton_e->setFont(font2);
        panelButton_e->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_e->setFocusPolicy(Qt::NoFocus);
        panelButton_e->setProperty("buttonValue", QVariant(QChar(101)));
        panelButton_t = new QPushButton(ProgramName);
        panelButton_t->setObjectName(QString::fromUtf8("panelButton_t"));
        panelButton_t->setGeometry(QRect(226, 160, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_t->sizePolicy().hasHeightForWidth());
        panelButton_t->setSizePolicy(sizePolicy);
        panelButton_t->setMinimumSize(QSize(45, 40));
        panelButton_t->setFont(font2);
        panelButton_t->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_t->setFocusPolicy(Qt::NoFocus);
        panelButton_t->setProperty("buttonValue", QVariant(QChar(116)));
        panelButton_m = new QPushButton(ProgramName);
        panelButton_m->setObjectName(QString::fromUtf8("panelButton_m"));
        panelButton_m->setGeometry(QRect(318, 244, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_m->sizePolicy().hasHeightForWidth());
        panelButton_m->setSizePolicy(sizePolicy);
        panelButton_m->setMinimumSize(QSize(45, 40));
        panelButton_m->setFont(font2);
        panelButton_m->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_m->setFocusPolicy(Qt::NoFocus);
        panelButton_m->setProperty("buttonValue", QVariant(QChar(109)));
        panelButton_Plus = new QPushButton(ProgramName);
        panelButton_Plus->setObjectName(QString::fromUtf8("panelButton_Plus"));
        panelButton_Plus->setGeometry(QRect(364, 244, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_Plus->sizePolicy().hasHeightForWidth());
        panelButton_Plus->setSizePolicy(sizePolicy);
        panelButton_Plus->setMinimumSize(QSize(45, 40));
        panelButton_Plus->setFont(font2);
        panelButton_Plus->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_Plus->setFocusPolicy(Qt::NoFocus);
        panelButton_Plus->setProperty("buttonValue", QVariant(QChar(0)));
        panelButton_d = new QPushButton(ProgramName);
        panelButton_d->setObjectName(QString::fromUtf8("panelButton_d"));
        panelButton_d->setGeometry(QRect(154, 202, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_d->sizePolicy().hasHeightForWidth());
        panelButton_d->setSizePolicy(sizePolicy);
        panelButton_d->setMinimumSize(QSize(45, 40));
        panelButton_d->setFont(font2);
        panelButton_d->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_d->setFocusPolicy(Qt::NoFocus);
        panelButton_d->setProperty("buttonValue", QVariant(QChar(100)));
        panelButton_u = new QPushButton(ProgramName);
        panelButton_u->setObjectName(QString::fromUtf8("panelButton_u"));
        panelButton_u->setGeometry(QRect(318, 160, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_u->sizePolicy().hasHeightForWidth());
        panelButton_u->setSizePolicy(sizePolicy);
        panelButton_u->setMinimumSize(QSize(45, 40));
        panelButton_u->setFont(font2);
        panelButton_u->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_u->setFocusPolicy(Qt::NoFocus);
        panelButton_u->setProperty("buttonValue", QVariant(QChar(117)));
        panelButton_w = new QPushButton(ProgramName);
        panelButton_w->setObjectName(QString::fromUtf8("panelButton_w"));
        panelButton_w->setGeometry(QRect(88, 160, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_w->sizePolicy().hasHeightForWidth());
        panelButton_w->setSizePolicy(sizePolicy);
        panelButton_w->setMinimumSize(QSize(45, 40));
        panelButton_w->setFont(font2);
        panelButton_w->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_w->setFocusPolicy(Qt::NoFocus);
        panelButton_w->setProperty("buttonValue", QVariant(QChar(119)));
        panelButton_n = new QPushButton(ProgramName);
        panelButton_n->setObjectName(QString::fromUtf8("panelButton_n"));
        panelButton_n->setGeometry(QRect(272, 244, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_n->sizePolicy().hasHeightForWidth());
        panelButton_n->setSizePolicy(sizePolicy);
        panelButton_n->setMinimumSize(QSize(45, 40));
        panelButton_n->setFont(font2);
        panelButton_n->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_n->setFocusPolicy(Qt::NoFocus);
        panelButton_n->setProperty("buttonValue", QVariant(QChar(110)));
        panelButton_s = new QPushButton(ProgramName);
        panelButton_s->setObjectName(QString::fromUtf8("panelButton_s"));
        panelButton_s->setGeometry(QRect(108, 202, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_s->sizePolicy().hasHeightForWidth());
        panelButton_s->setSizePolicy(sizePolicy);
        panelButton_s->setMinimumSize(QSize(45, 40));
        panelButton_s->setFont(font2);
        panelButton_s->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_s->setFocusPolicy(Qt::NoFocus);
        panelButton_s->setProperty("buttonValue", QVariant(QChar(115)));
        panelButton_7 = new QPushButton(ProgramName);
        panelButton_7->setObjectName(QString::fromUtf8("panelButton_7"));
        panelButton_7->setGeometry(QRect(318, 115, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_7->sizePolicy().hasHeightForWidth());
        panelButton_7->setSizePolicy(sizePolicy);
        panelButton_7->setMinimumSize(QSize(45, 40));
        panelButton_7->setFont(font2);
        panelButton_7->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_7->setFocusPolicy(Qt::NoFocus);
        panelButton_7->setProperty("buttonValue", QVariant(QChar(55)));
        panelButton_g = new QPushButton(ProgramName);
        panelButton_g->setObjectName(QString::fromUtf8("panelButton_g"));
        panelButton_g->setGeometry(QRect(246, 202, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_g->sizePolicy().hasHeightForWidth());
        panelButton_g->setSizePolicy(sizePolicy);
        panelButton_g->setMinimumSize(QSize(45, 40));
        panelButton_g->setFont(font2);
        panelButton_g->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_g->setFocusPolicy(Qt::NoFocus);
        panelButton_g->setProperty("buttonValue", QVariant(QChar(103)));
        panelButton_q = new QPushButton(ProgramName);
        panelButton_q->setObjectName(QString::fromUtf8("panelButton_q"));
        panelButton_q->setGeometry(QRect(42, 160, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_q->sizePolicy().hasHeightForWidth());
        panelButton_q->setSizePolicy(sizePolicy);
        panelButton_q->setMinimumSize(QSize(45, 40));
        panelButton_q->setFont(font2);
        panelButton_q->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_q->setFocusPolicy(Qt::NoFocus);
        panelButton_q->setProperty("buttonValue", QVariant(QChar(113)));
        panelButton_9 = new QPushButton(ProgramName);
        panelButton_9->setObjectName(QString::fromUtf8("panelButton_9"));
        panelButton_9->setGeometry(QRect(410, 115, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_9->sizePolicy().hasHeightForWidth());
        panelButton_9->setSizePolicy(sizePolicy);
        panelButton_9->setMinimumSize(QSize(45, 40));
        panelButton_9->setFont(font2);
        panelButton_9->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_9->setFocusPolicy(Qt::NoFocus);
        panelButton_9->setProperty("buttonValue", QVariant(QChar(57)));
        panelButton_1 = new QPushButton(ProgramName);
        panelButton_1->setObjectName(QString::fromUtf8("panelButton_1"));
        panelButton_1->setGeometry(QRect(42, 115, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_1->sizePolicy().hasHeightForWidth());
        panelButton_1->setSizePolicy(sizePolicy);
        panelButton_1->setMinimumSize(QSize(45, 40));
        panelButton_1->setFont(font2);
        panelButton_1->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_1->setFocusPolicy(Qt::NoFocus);
        panelButton_1->setProperty("buttonValue", QVariant(QChar(49)));
        panelButton_6 = new QPushButton(ProgramName);
        panelButton_6->setObjectName(QString::fromUtf8("panelButton_6"));
        panelButton_6->setGeometry(QRect(272, 115, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_6->sizePolicy().hasHeightForWidth());
        panelButton_6->setSizePolicy(sizePolicy);
        panelButton_6->setMinimumSize(QSize(45, 40));
        panelButton_6->setFont(font2);
        panelButton_6->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_6->setFocusPolicy(Qt::NoFocus);
        panelButton_6->setProperty("buttonValue", QVariant(QChar(54)));
        panelButton_z = new QPushButton(ProgramName);
        panelButton_z->setObjectName(QString::fromUtf8("panelButton_z"));
        panelButton_z->setGeometry(QRect(42, 244, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_z->sizePolicy().hasHeightForWidth());
        panelButton_z->setSizePolicy(sizePolicy);
        panelButton_z->setMinimumSize(QSize(45, 40));
        panelButton_z->setFont(font2);
        panelButton_z->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_z->setFocusPolicy(Qt::NoFocus);
        panelButton_z->setProperty("buttonValue", QVariant(QChar(122)));
        panelButton_star = new QPushButton(ProgramName);
        panelButton_star->setObjectName(QString::fromUtf8("panelButton_star"));
        panelButton_star->setGeometry(QRect(456, 244, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_star->sizePolicy().hasHeightForWidth());
        panelButton_star->setSizePolicy(sizePolicy);
        panelButton_star->setMinimumSize(QSize(45, 40));
        panelButton_star->setFont(font2);
        panelButton_star->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_star->setFocusPolicy(Qt::NoFocus);
        panelButton_star->setProperty("buttonValue", QVariant(QChar(46)));
        panelButton_3 = new QPushButton(ProgramName);
        panelButton_3->setObjectName(QString::fromUtf8("panelButton_3"));
        panelButton_3->setGeometry(QRect(134, 115, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_3->sizePolicy().hasHeightForWidth());
        panelButton_3->setSizePolicy(sizePolicy);
        panelButton_3->setMinimumSize(QSize(45, 40));
        panelButton_3->setFont(font2);
        panelButton_3->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_3->setFocusPolicy(Qt::NoFocus);
        panelButton_3->setProperty("buttonValue", QVariant(QChar(51)));
        panelButton_k = new QPushButton(ProgramName);
        panelButton_k->setObjectName(QString::fromUtf8("panelButton_k"));
        panelButton_k->setGeometry(QRect(384, 202, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_k->sizePolicy().hasHeightForWidth());
        panelButton_k->setSizePolicy(sizePolicy);
        panelButton_k->setMinimumSize(QSize(45, 40));
        panelButton_k->setFont(font2);
        panelButton_k->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_k->setFocusPolicy(Qt::NoFocus);
        panelButton_k->setProperty("buttonValue", QVariant(QChar(107)));
        programName_cancal = new QPushButton(ProgramName);
        programName_cancal->setObjectName(QString::fromUtf8("programName_cancal"));
        programName_cancal->setGeometry(QRect(512, 160, 61, 41));
        programName_cancal->setFont(font1);
        panelButton_l = new QPushButton(ProgramName);
        panelButton_l->setObjectName(QString::fromUtf8("panelButton_l"));
        panelButton_l->setGeometry(QRect(430, 202, 45, 40));
        sizePolicy.setHeightForWidth(panelButton_l->sizePolicy().hasHeightForWidth());
        panelButton_l->setSizePolicy(sizePolicy);
        panelButton_l->setMinimumSize(QSize(45, 40));
        panelButton_l->setFont(font2);
        panelButton_l->setCursor(QCursor(Qt::ArrowCursor));
        panelButton_l->setFocusPolicy(Qt::NoFocus);
        panelButton_l->setProperty("buttonValue", QVariant(QChar(108)));

        retranslateUi(ProgramName);
        QObject::connect(programName_cancal, SIGNAL(clicked()), ProgramName, SLOT(close()));

        QMetaObject::connectSlotsByName(ProgramName);
    } // setupUi

    void retranslateUi(QDialog *ProgramName)
    {
        ProgramName->setWindowTitle(QApplication::translate("ProgramName", "Dialog", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("ProgramName", "\350\276\223\345\205\245\347\250\213\345\272\217\345\220\215\357\274\232", 0, QApplication::UnicodeUTF8));
        label_isEmpty->setText(QString());
        panelButton_b->setText(QApplication::translate("ProgramName", "B", 0, QApplication::UnicodeUTF8));
        panelButton_a->setText(QApplication::translate("ProgramName", "A", 0, QApplication::UnicodeUTF8));
        panelButton_r->setText(QApplication::translate("ProgramName", "R", 0, QApplication::UnicodeUTF8));
        panelButton_v->setText(QApplication::translate("ProgramName", "V", 0, QApplication::UnicodeUTF8));
        panelButton_j->setText(QApplication::translate("ProgramName", "J", 0, QApplication::UnicodeUTF8));
        BackButton->setText(QApplication::translate("ProgramName", "\345\210\240\351\231\244", 0, QApplication::UnicodeUTF8));
        panelButton_f->setText(QApplication::translate("ProgramName", "F", 0, QApplication::UnicodeUTF8));
        panelButton_5->setText(QApplication::translate("ProgramName", "5", 0, QApplication::UnicodeUTF8));
        panelButton_2->setText(QApplication::translate("ProgramName", "2", 0, QApplication::UnicodeUTF8));
        panelButton_x->setText(QApplication::translate("ProgramName", "X", 0, QApplication::UnicodeUTF8));
        programName_confirm->setText(QApplication::translate("ProgramName", "\347\241\256\350\256\244", 0, QApplication::UnicodeUTF8));
        panelButton_4->setText(QApplication::translate("ProgramName", "4", 0, QApplication::UnicodeUTF8));
        panelButton_o->setText(QApplication::translate("ProgramName", "O", 0, QApplication::UnicodeUTF8));
        panelButton_c->setText(QApplication::translate("ProgramName", "C", 0, QApplication::UnicodeUTF8));
        panelButton_i->setText(QApplication::translate("ProgramName", "I", 0, QApplication::UnicodeUTF8));
        panelButton_p->setText(QApplication::translate("ProgramName", "P", 0, QApplication::UnicodeUTF8));
        panelButton_Dec->setText(QApplication::translate("ProgramName", "#", 0, QApplication::UnicodeUTF8));
        panelButton_y->setText(QApplication::translate("ProgramName", "Y", 0, QApplication::UnicodeUTF8));
        panelButton_h->setText(QApplication::translate("ProgramName", "H", 0, QApplication::UnicodeUTF8));
        panelButton_0->setText(QApplication::translate("ProgramName", "0", 0, QApplication::UnicodeUTF8));
        panelButton_8->setText(QApplication::translate("ProgramName", "8", 0, QApplication::UnicodeUTF8));
        panelButton_e->setText(QApplication::translate("ProgramName", "E", 0, QApplication::UnicodeUTF8));
        panelButton_t->setText(QApplication::translate("ProgramName", "T", 0, QApplication::UnicodeUTF8));
        panelButton_m->setText(QApplication::translate("ProgramName", "M", 0, QApplication::UnicodeUTF8));
        panelButton_Plus->setText(QApplication::translate("ProgramName", "*", 0, QApplication::UnicodeUTF8));
        panelButton_d->setText(QApplication::translate("ProgramName", "D", 0, QApplication::UnicodeUTF8));
        panelButton_u->setText(QApplication::translate("ProgramName", "U", 0, QApplication::UnicodeUTF8));
        panelButton_w->setText(QApplication::translate("ProgramName", "W", 0, QApplication::UnicodeUTF8));
        panelButton_n->setText(QApplication::translate("ProgramName", "N", 0, QApplication::UnicodeUTF8));
        panelButton_s->setText(QApplication::translate("ProgramName", "S", 0, QApplication::UnicodeUTF8));
        panelButton_7->setText(QApplication::translate("ProgramName", "7", 0, QApplication::UnicodeUTF8));
        panelButton_g->setText(QApplication::translate("ProgramName", "G", 0, QApplication::UnicodeUTF8));
        panelButton_q->setText(QApplication::translate("ProgramName", "Q", 0, QApplication::UnicodeUTF8));
        panelButton_9->setText(QApplication::translate("ProgramName", "9", 0, QApplication::UnicodeUTF8));
        panelButton_1->setText(QApplication::translate("ProgramName", "1", 0, QApplication::UnicodeUTF8));
        panelButton_6->setText(QApplication::translate("ProgramName", "6", 0, QApplication::UnicodeUTF8));
        panelButton_z->setText(QApplication::translate("ProgramName", "Z", 0, QApplication::UnicodeUTF8));
        panelButton_star->setText(QApplication::translate("ProgramName", "-", 0, QApplication::UnicodeUTF8));
        panelButton_3->setText(QApplication::translate("ProgramName", "3", 0, QApplication::UnicodeUTF8));
        panelButton_k->setText(QApplication::translate("ProgramName", "K", 0, QApplication::UnicodeUTF8));
        programName_cancal->setText(QApplication::translate("ProgramName", "\345\217\226\346\266\210", 0, QApplication::UnicodeUTF8));
        panelButton_l->setText(QApplication::translate("ProgramName", "L", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class ProgramName: public Ui_ProgramName {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PROGRAMNAME_H
